MLK-22283 env: fix NAND ENV build issue introduced by env offset change
Get below build error in nand env, because we should not call function in
array initialization.

env/nand.c: In function ‘env_nand_save’:
env/nand.c:196:15: error: initializer element is not constant
.offset = env_get_offset(CONFIG_ENV_OFFSET),

Signed-off-by: Ye Li <ye.li@nxp.com>
(cherry picked from commit da33243320c9ebbde3f343aee7623028a440a024)