MLK-19218 imx8qm/qxp: spl: Fix build break in SPL build
Get such build error below due to the changes in tcpc.h
(MLK-19181-2: i.MX850: SPL enable usb support).
Fix the issue by removing unused tcpc and usb header files from spl.c

spl/board/freescale/imx8qxp_mek/spl.o: In function `tcpc_setup_ufp_mode':
spl.c:(.text.tcpc_setup_ufp_mode+0x0): multiple definition of `tcpc_setup_ufp_mode'
spl/board/freescale/imx8qxp_mek/imx8qxp_mek.o:imx8qxp_mek.c:(.text.tcpc_setup_ufp_mode+0x0): first defined here
spl/board/freescale/imx8qxp_mek/spl.o: In function `tcpc_setup_dfp_mode':
spl.c:(.text.tcpc_setup_dfp_mode+0x0): multiple definition of `tcpc_setup_dfp_mode'
spl/board/freescale/imx8qxp_mek/imx8qxp_mek.o:/home/leyoen/Workspace/u-boot-upgrading/u-boot/board/freescale/imx8qxp_mek/imx8qxp_mek.c:547: first defined here
scripts/Makefile.build:359: recipe for target 'spl/board/freescale/imx8qxp_mek/built-in.o' failed

Signed-off-by: Ye Li <ye.li@nxp.com>