[iot] Fix 'calc_sha256' not defined error
'calc_sha256' should only be valid when CONFIG_IMX_TRUSTY_OS
is defined. Error message is like below:
  error: label 'calc_sha256' defined but not used
	[-Werror=unused-label]

Test: build pass with or without CONFIG_IMX_TRUSTY_OS enabled.

Change-Id: I0938e641596cb9faccd0c64f7c03d526dab3b7d4
Signed-off-by: Luo Ji <ji.luo@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/4932
Reviewed-by: Wang Haoran <elven.wang@nxp.com>